export const DEC_ITEM_QTY="DEC_ITEM_QTY";
export const INC_ITEM_QTY="INC_ITEM_QTY";
export const CART_REQUEST="CART_REQUEST";
export const CART_FAILURE="CART_FAILURE";
export const UPDATECART="UPDATECART";
export const DELETECART="DELETECART";
export const ADDTOCART="DELETECART";
// export const LOGIN_SUCCESS="LOGIN_SUCCESS";
// export const AUTH_REQUEST=" AUTH_REQUEST";
// export const AUTH_ERROR="AUTH_ERROR";
// export const AUTH_SUCCESS="AUTH_SUCCESS";
// export const LOGIN_REQUEST="LOGIN_REQUEST";
// export const LOGOUT_REQUEST="LOGOUT_REQUEST";
// export const LOGIN_FAILURE="LOGIN_FAILURE";

