export const PRODUCT_REQUEST_ARRIVAL = "PRODUCT_REQUEST_ARRIVAL";
export const PRODUCT_REQUEST_RINGS = "PRODUCT_REQUEST_RINGS";
export const PRODUCT_REQUEST_EARRINGS = "PRODUCT_REQUEST_EARRINGS";
export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST_CART";
export const PRODUCT_REQUEST_BRACELETS = "PRODUCT_REQUEST_BRACELETS";
export const IsLoading = "isLoading";
export const IsError = "isError";
export const TOTALPAGE = "TOTALPAGE";

